### ISSUE TITLE
How to Implement BeforeClass and AfterClass? 

### ISSUE THREAD

**Issue by ramkumary** [webdriverextensions/webdriverextensions#95] opened 2017-05-09 08:48 UTC
I would like to implement BeforeClass and AfterClass feature. Since it is a JunitRunner extension, I am clueless to identify the exact method to integrate the Before/After Class calls. These methods has to be called from Before/After class not with @Before,@After

Thanks,
RKY

**Comment by andidev** [comment] 2017-05-09 14:19
BeforeClass and AfterClass should work. However the driver is not available at that time since the driver gets created for each test method and browser annotation. 

What are you trying to achieve in BeforeClass AfterClass?

**Comment by ramkumary** [comment] 2017-05-09 18:01
I would like to initialize the reporting class and close the reporter after class. So that all the methods will be reported in the single file.

**Comment by andidev** [comment] 2017-05-18 18:49
So I just tried the `@BeforeClass` and `@AfterClass` JUnit annotations and they seem to work. 

The following:
```
@RunWith(WebDriverRunner.class)
@Chrome
@Firefox
public class BotTest {

    @BeforeClass
    public static void beforeClass() {
        System.out.println("Running before class");
    }

    @AfterClass
    public static void afterClass() {
        System.out.println("Running after class");
    }

    ...the tests
}
```

Outputs:
```
20:45 15   INFO    Browsers disabled by system property: []                                                                                             WebDriverRunner:172 
Running before class
20:45 20   INFO    Running test BotTest.clickTest@Chrome                                                                                                WebDriverRunner:317 
20:45 26   INFO    Running test BotTest.clickTest@Firefox                                                                                               WebDriverRunner:317 
20:45 31   INFO    Running test BotTest.typeTest@Chrome                                                                                                 WebDriverRunner:317 
20:45 38   INFO    Running test BotTest.typeTest@Firefox                                                                                                WebDriverRunner:317 
Running after class

Process finished with exit code 0
```

Is this not the expected behaviour?

**Comment by ramkumary** [comment] 2017-06-09 07:24
That is right. But it should static. I have a classification or Pages/Tests. All of my pages are non-static. 
Assume I have to call the login from Login Page which is non-static. Now it does not allow me to call and I have to change all of them. On another hand, Why not override the classBlock to accommodate the same in the WebDriverRunner?

A couple of reference for your attention.

https://stackoverflow.com/questions/15141593/custom-blockjunit4classrunner-which-runs-test-suite-set-number-of-times

https://stackoverflow.com/questions/25720758/in-junit-4-is-there-a-way-to-run-a-piece-of-code-before-all-beforeclass-in-a-c

I am trying to integrate the class block and could not succeed. Might be I am wrong in the approach.

Thanks,
Ram

**Comment by andidev** [comment] 2017-06-14 19:28
I don't think you can interact with WebDriver from BeforeClass and AfterClass since the driver gets created for each tests. I'm closing this since you have created other issues according to this problem and the main question is working as it should according to JUnit docs.

**Closed by andidev** 2017-06-14 19:28 UTC
Labels: question
