### ISSUE TITLE
Questions related to Before and After Class

### ISSUE THREAD

**Issue by ramkumary** [webdriverextensions/webdriverextensions#92] opened 2017-05-03 07:05 UTC
My apologies, I have too many questions to ask.

1) How about Before class and After Class. When I try to implement, I am getting WebDriver is not set error.
2) How about logging each Bot methods? Do we have an interface for that or How to extend that? I am interested in logging all Bot method activities from log4j or custom reporter?
3) How about WebDriverEventListener interface implementation? I tried to implement the same as given below.

```
public class WebDriverEventCustomListener implements WebDriverEventListener {

	private static final Logger log = LoggerFactory.getLogger(WebDriverEventCustomListener.class);
	
	public void beforeClickOn(final WebElement arg0, final WebDriver arg1) {
		log.info(arg0.getText() + " is clicked.");
	}

	public void afterClickOn(final WebElement arg0, final WebDriver arg1) {

	}

	public void beforeFindBy(final By arg0, final WebElement arg1, final WebDriver arg2) {

	}

	public void afterFindBy(final By arg0, final WebElement arg1, final WebDriver arg2) {
	}

	public void afterNavigateTo(final String arg0, final WebDriver arg1) {

	}

	public void onException(final Throwable arg0, final WebDriver arg1) {
		try {
			log.info("Exception occured." + arg0.getStackTrace());
		} catch (Exception e) {
		}
	}

	public void afterAlertAccept(final WebDriver arg0) {

	}

	public void afterAlertDismiss(final WebDriver arg0) {

	}

	public void afterChangeValueOf(final WebElement arg0, final WebDriver arg1, final CharSequence[] arg2) {
		log.info(arg0.getText() + " is chnaged with " + arg2.toString());
	}

	public void afterNavigateBack(final WebDriver arg0) {

	}

	public void afterNavigateForward(final WebDriver arg0) {

	}

	public void afterNavigateRefresh(final WebDriver arg0) {
	}

	public void afterScript(final String arg0, final WebDriver arg1) {

	}

	public void beforeAlertAccept(final WebDriver arg0) {

	}

	public void beforeAlertDismiss(final WebDriver arg0) {

	}

	public void beforeChangeValueOf(final WebElement arg0, final WebDriver arg1, final CharSequence[] arg2) {

	}

	public void beforeNavigateTo(String url, WebDriver driver) {
		log.info("Navigating to " + url);
	}

	public void beforeNavigateBack(WebDriver driver) {

	}

	public void beforeNavigateForward(WebDriver driver) {

	}

	public void beforeNavigateRefresh(WebDriver driver) {

	}

	public void beforeScript(String script, WebDriver driver) {

	}
}
```

However, it is not hitting the implementation other than Navigate to a method.

**Comment by andidev** [comment] 2017-05-03 13:22
1) A new driver is created for each test method and browser configuration so the driver is not available when @BeforeClass runs. It should however be available when @Before runs:
The following:
```java
   @Before
    public void beforeTest(){
        System.out.println("driver = " + WebDriverExtensionsContext.getDriver());
    }
```
should for example print:
```
driver = ChromeDriver: chrome on MAC (26545ae8265b75a4cc0fbae58c326576)
```

2) There is currently no Interface that could be extended to log the Bot methods. PR's are welcome, maybe needs some discussion before on what the best approach would be.  

3) I am unfamiliar with the WebDriverEventListener. How do you apply that to your driver?
Is this the correct way to do so?
```
EventFiringWebDriver eventDriver = new EventFiringWebDriver(driver);
eventDriver.register(listener);
```
This is however not implemented in the WebDriverRunner when the driver is created. Though it could easily be added.

**Comment by ramkumary** [comment] 2017-05-03 16:24
Thank you very much for your detailed answer.

Q2 - We have multiple options.
        a) log4j
        b) xml + xsl 
        c) ExtentReports - I found this is interesting and exhausitive options [http://extentreports.com/samples/extent.html](url)
       
Q3)  This interface will listen to all the events triggered from WebDriver. Actual interface link [https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/support/events/WebDriverEventListener.html](link)

Here is the sample binding

```
@BeforeClass
	public static void setupBeforeClass() {
		if (WebDriverExtensionsContext.getDriver() != null)
			EventFiringCapabilities.attachEventFiringCapabilities();
	}

public static void attachEventFiringCapabilities() {
		EventFiringWebDriver eventFiringDriver = new EventFiringWebDriver(WebDriverExtensionsContext.getDriver());
		WebDriverEventCustomListener eventHandler = new WebDriverEventCustomListener();
		eventFiringDriver.register(eventHandler);
		WebDriverExtensionsContext.setDriver(eventFiringDriver);
	}

```

**Comment by andidev** [comment] 2017-05-04 09:37
Q3) Aha okay so I got the eventlistner to work. The problem is that you need to re-initialise the WebElements with the PageFactory and the new EventFiringWebDriver webdriver.

you need to add the folowing line to your attachEventFiringCapabilities(Object testClass) method (note that you need to pass the testClass).
```java
            PageFactory.initElements(new WebDriverExtensionFieldDecorator(WebDriverExtensionsContext.getDriver()), testClass);
```

Here is a complete example:
```java
package com.github.webdriverextensions;

import com.github.webdriverextensions.junitrunner.WebDriverRunner;
import com.github.webdriverextensions.junitrunner.annotations.Chrome;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.PageFactory;
import org.openqa.selenium.support.events.AbstractWebDriverEventListener;
import org.openqa.selenium.support.events.EventFiringWebDriver;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import static com.github.webdriverextensions.Bot.click;
import static com.github.webdriverextensions.Bot.open;

@RunWith(WebDriverRunner.class)
@Chrome
public class EventListnerClickTest {

    @FindBy(css = "[href=\"/html/default.asp\"]")
    public WebElement learnHtmlButton;

    @Before
    public void beforeTest() {
        EventFiringCapabilities.attachEventFiringCapabilities(this);
        open("https://www.w3schools.com/");
    }

    @Test
    public void clickTest() {
        click(learnHtmlButton);
    }

    public static class EventFiringCapabilities {
        public static void attachEventFiringCapabilities(Object testClass) {
            EventFiringWebDriver eventFiringDriver = new EventFiringWebDriver(WebDriverExtensionsContext.getDriver());
            WebDriverEventCustomListener eventHandler = new WebDriverEventCustomListener();
            eventFiringDriver.register(eventHandler);
            WebDriverExtensionsContext.setDriver(eventFiringDriver);
            PageFactory.initElements(new WebDriverExtensionFieldDecorator(WebDriverExtensionsContext.getDriver()), testClass);
        }
    }

    public static class WebDriverEventCustomListener extends AbstractWebDriverEventListener {

        private static final Logger log = LoggerFactory.getLogger(WebDriverEventCustomListener.class);

        public void beforeClickOn(final WebElement arg0, final WebDriver arg1) {
            log.info(arg0.getText() + " is clicked.");
        }

    }

}
```

**Comment by ramkumary** [comment] 2017-05-08 06:59
Thank you very much.

**Comment by andidev** [comment] 2017-05-18 18:36
Si I'm closing this since it looks resolved. Please comment otherwise.

**Closed by andidev** 2017-05-18 18:36 UTC
